"""Add fabric and color models

Revision ID: 41832a8aee86
Revises: 
Create Date: 2025-09-24 17:40:31.063444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41832a8aee86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fabric_families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fabric_families_family_id'), 'fabric_families', ['family_id'], unique=True)
    op.create_index(op.f('ix_fabric_families_id'), 'fabric_families', ['id'], unique=False)
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fabric_family_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hex_value', sa.String(), nullable=False),
    sa.Column('swatch_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fabric_family_id'], ['fabric_families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colors_color_id'), 'colors', ['color_id'], unique=True)
    op.create_index(op.f('ix_colors_fabric_family_id'), 'colors', ['fabric_family_id'], unique=False)
    op.create_index(op.f('ix_colors_id'), 'colors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_colors_id'), table_name='colors')
    op.drop_index(op.f('ix_colors_fabric_family_id'), table_name='colors')
    op.drop_index(op.f('ix_colors_color_id'), table_name='colors')
    op.drop_table('colors')
    op.drop_index(op.f('ix_fabric_families_id'), table_name='fabric_families')
    op.drop_index(op.f('ix_fabric_families_family_id'), table_name='fabric_families')
    op.drop_table('fabric_families')
    # ### end Alembic commands ###
